# Generated by Django 4.1.3 on 2022-11-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('passwd', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'blog_users',
            },
        ),
    ]
