FROM mysql:5.7

# RUN apt-get update
# RUN intall -y mysql-server-5.7
# RUN apt install --no-install-recommends -y tzdata
# RUN apt clean
# RUN cd bin
# RUN mysql grant all privileges on *.* to 'root'@'%' identified by 'root'
# RUN cd /

# COPY conf.d/my.cnf etc/mysql/my.cnf

# ENTRYPOINT grant all privileges on *.* to 'root'@'%' identified by 'root';
# RUN grant all privileges on *.* to 'root'@'%' identified by 'root';