# Generated by Django 4.1.3 on 2022-12-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('birth', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('user_interests', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'exrc_users',
            },
        ),
    ]
