# Generated by Django 4.1.3 on 2022-11-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('image_url', models.TextField()),
                ('address', models.CharField(max_length=50)),
                ('detail_address', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'movie_cinemas',
            },
        ),
    ]
