# Generated by Django 4.1.3 on 2022-11-30 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exrc_posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('exrc_posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exrc_posts.post')),
            ],
            options={
                'db_table': 'blog_tags',
            },
        ),
    ]
