# Generated by Django 4.1.3 on 2022-11-30 06:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_users', '0001_initial'),
        ('deliveries', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('delivery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.delivery')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_users.shopuser')),
            ],
            options={
                'db_table': 'shop_orders',
            },
        ),
    ]
