# Generated by Django 4.1.3 on 2022-12-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('passwd', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
