# Generated by Django 4.1.3 on 2022-12-22 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exrc_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='exrc_users',
        ),
    ]
